version: '3.5'

services:
  ctfd:
    build:
      context: .
      args:
        - WORKDIR=/opt/CTFd
    image: bitnsc-ctfd-main
    user: root
    restart: always
    ports:
      - 80:8000
    environment:
      - SECRET_KEY=random_this
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd # 格式：mysql+pymysql://<MYSQL_USER>:<MYSQL_PASSWORD>@db/<MYSQL_DATABASE>
      - REDIS_URL=redis://cache:6379/0
      - WORKERS=4
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=/var/log/CTFd/access.log
      - ERROR_LOG=/var/log/CTFd/error.log
      - PROBLEM_DOCKER_RUN_FOLDER=/home/docker # 题目容器运行的文件夹，保证与下方 volumes 中的一致 
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd
      - /home/docker:/home/docker # 宿主机和容器的映射目录和 PROBLEM_DOCKER_RUN_FOLDER 一致，保证题目创建时不会出现找不到题目容器的映射目录等情况
      - /var/run/docker.sock:/var/run/docker.sock # 保证通过容器的 docker.sock 能操作宿主机的 docker.sock
    depends_on:
      - db
      - frpc
    networks:
      default:
      internal:
      frp:
        ipv4_address: 10.1.0.5

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
       internal:

  frps:
    image: spaceskynet/bitnsc-frp
    # you can build image by yourself if you want.
    #build: ./frp
    restart: always
    volumes:
      - ./frp/conf:/conf/
    expose:
      - 80
    ports:
      - 20000-20099:20000-20099
    entrypoint:
      - /app/frps
      - -c
      - /conf/frps.ini
    networks:
      default:
      frp:
        ipv4_address: 10.1.0.3

  frpc:
    image: spaceskynet/bitnsc-frp
    # you can build image by yourself if you want.
    #build: ./frp
    restart: always
    volumes:
      - ./frp/conf:/conf/
    expose:
      - 7400
    entrypoint:
      - /app/frpc
      - -c
      - /conf/frpc.ini
    networks:
      frp:
        ipv4_address: 10.1.0.4
      frp_containers:

networks:
    default:
      name: "bitnsc_default"
    internal:
      name: "bitnsc_internal"
      internal: true
    frp:
      name: "bitnsc_frp"
      driver: bridge
      ipam:
        config:
          - subnet: 10.1.0.0/16
    frp_containers:
      name: "bitnsc_frp_containers"
      driver: bridge
      ipam:
        config:
          - subnet: 10.2.0.0/16
